Document running from GitLab CI/CD
gatling/frontline-cloud-doc pull request #127
Opened 2023-02-17 15:14 UTC by guilgaly

Note: I added Gradle Wrapper to the examples (also for the existing GitHub Actions doc), because I think it's very common among Gradle users?

2023-02-17 15:49 UTC, slandelle approved these changes
Great!

2023-02-17 16:37 UTC, tpetillot commented on content/reference/plugins/script/index.md
> +You can build you Simulation, and then run the updated Simulation on Gatling Enterprise, using the `enterpriseRun` command with any of our supported build tools.
```suggestion
You can build you Simulation, and then run the updated Simulation on Gatling Enterprise, using the `enterpriseStart` command with any of our supported build tools.
```

2023-02-20 08:53 UTC, notdryft requested changes

2023-02-20 08:53 UTC, notdryft commented on content/reference/plugins/script/index.md
> +We provide dedicated support for a number of CI systems: [GitHub Actions]({{< ref "../github_actions" >}}), [Gitlab CI]({{< ref "../gitlab_ci" >}}), [Jenkins]({{< ref "../jenkins" >}}), [Teamcity]({{
```suggestion
We provide dedicated support for a number of CI tools: [GitHub Actions]({{< ref "../github_actions" >}}), [Gitlab CI]({{< ref "../gitlab_ci" >}}), [Jenkins]({{< ref "../jenkins" >}}), [Teamcity]({{< ref "../teamcity" >}}), [Bamboo]({{< ref "../github_actions" >}}). However, we also document here how to run your simulations on Gatling Enterprise from any other CI products, using either one of the supported build tools or our CI shell script.
```

2023-02-20 13:58 UTC, merged