doc: reorganized private locations documentation tree, closes HYB-168
gatling/frontline-cloud-doc pull request #129
Opened 2023-02-28 10:27 UTC by tpetillot

[doc: reword private locations configuration page](https://github.com/gatling/frontline-cloud-doc/commit/64192a5531d27e6b29366e93a63f83f9947c38db)

[doc: document control plane token with environment variable and system property](https://github.com/gatling/frontline-cloud-doc/commit/972807a61b8853af421aa1668ecd89f9f713ac2d) 

[doc: reorganized private locations documentation tree, closes HYB-168](https://github.com/gatling/frontline-cloud-doc/commit/de103c93d700ddf163c76bb35ed17f9a5c9a7446) 

**Modifications:**

Private locations documentation tree is now:
* Introduction
* Configuration
  * AWS EC2
  * Kubernetes
* Deployment
  * ECS
  * Kubernetes

2023-02-28 13:29 UTC, slandelle requested changes
* `Deployment` is too vague for me. Installation?
* Shouldn't Installation go BEFORE Configuration?
* Isn't there a common configuration bloc, in particular the token? Shouldn't we have a dedicated section?
* AWS EC2 (too vague) => AWS EC2 Load Generators
* Kubernetes (too vague) => Kubernetes Load Generators

2023-03-02 12:51 UTC, slandelle requested changes

2023-03-02 12:51 UTC, slandelle commented on content/reference/admin/private_locations/_index.md
> +  - deployment
forgot to rename here?

2023-03-21 13:15 UTC, bastien-gatling commented on content/reference/admin/private_locations/configuration/kubernetes/index.md
> +  token = $?control.plane.token
Same remark : i would comment the two other examples.

2023-03-22 09:39 UTC, tpetillot commented on content/reference/admin/private_locations/introduction/index.md
> +  token = $?control.plane.token
as it's an optional override, not sure if we should comment them.

2023-03-22 14:03 UTC, bastien-gatling approved these changes

2023-03-22 14:58 UTC, merged