doc: add control plane configuration for Azure private location
gatling/frontline-cloud-doc pull request #141
Opened 2023-03-31 14:35 UTC by Obero

2023-04-06 07:03 UTC, bastien-gatling reviewed
Pretty clear ! :)

2023-04-06 07:44 UTC, notdryft commented on content/reference/admin/private_locations/installation/azure/index.md
> +lead: "Run a Control Plane on Azure using Container Apps and Fargate, to set up your Private Locations and run load generators in your own Azure network"
Indeed

2023-04-06 09:33 UTC, Obero commented on content/reference/admin/private_locations/installation/azure/index.md
> +lead: "Run a Control Plane on Azure using Container Apps and Fargate, to set up your Private Locations and run load generators in your own Azure network"
Are you REALLY sure ? 🫥

2023-04-06 09:37 UTC, Obero commented on content/reference/admin/private_locations/installation/azure/index.md
> +Each configuration can be
Well, it shouldn't have been important, because I don't recall what I was going to say

2023-04-06 09:42 UTC, notdryft commented on content/reference/admin/private_locations/installation/azure/index.md
> +See [control plane configuration](/docs/cloud/reference/admin/private_locations/introduction/#configuration) sections of Gatling Cloud documentation for details.
```suggestion
See [control plane configuration]({{< ref "../../introduction#configuration" >}}) sections of Gatling Cloud documentation for details.
```

2023-04-06 12:26 UTC, notdryft requested changes

2023-04-06 12:26 UTC, notdryft commented on content/reference/admin/private_locations/installation/azure/index.md
> +* Indicate "gatlingcorp/control-plane:latest" in image and tag field
```suggestion
* Indicate `gatlingcorp/control-plane:latest` in image and tag field
```

2023-04-06 12:26 UTC, notdryft commented on content/reference/admin/private_locations/installation/azure/index.md
> +We strongly advise to set the minimum scale at 1, to ensure that your control plane will always be up.
```suggestion
We strongly advise to set the minimum scale to 1, to ensure that your control plane will always be up.
```

2023-04-06 12:26 UTC, notdryft commented on content/reference/admin/private_locations/installation/azure/index.md
> +Now that your control plane is up and running, after a short time you should see your control plane with "up" status in Gatling Enterprise Cloud.
```suggestion
Now that your control plane is up and running, after a short time you should see your control plane with {{< badge success >}}up{{< /badge >}} status in Gatling Enterprise Cloud.
```

2023-04-06 12:26 UTC, notdryft commented on content/reference/admin/private_locations/installation/azure/index.md
> +You can now configure a simulation to run one one or more of this Control Plane's pool!
```suggestion
You can now configure a simulation to run one or more of this Control Plane's pool!
```

2023-04-07 07:12 UTC, bastien-gatling approved these changes

2023-04-17 08:12 UTC, tpetillot approved these changes

2023-04-17 09:28 UTC, merged