doc: document control plane installation on GCP compute engine, closes HYB-363
gatling/frontline-cloud-doc pull request #166
Opened 2023-10-03 16:05 UTC by tpetillot

2023-10-04 05:45 UTC, stb13579 requested changes
Nice! Just a few minor English improvements and some formatting. In general, lists are better as bullet points for readability. Let me know if you need any clarification on my comments or suggestions.

2023-10-04 05:45 UTC, stb13579 commented on content/reference/admin/private_locations/installation/ecs/index.md
> +You can now configure a simulation to run one one or more of this Control Plane's location!
```suggestion
You can now configure a simulation to run on one or more of this Control Plane's locations!
```

2023-10-04 05:45 UTC, stb13579 commented on content/reference/admin/private_locations/installation/gcp/index.md
> +Click Create secret.
```suggestion
Click **CREATE SECRET**.
```

2023-10-04 05:45 UTC, stb13579 commented on content/reference/admin/private_locations/installation/gcp/index.md
> +Click Create secret.
Match the capitalization on the button and bold to indicate a button.

2023-10-04 05:45 UTC, stb13579 commented on content/reference/admin/private_locations/installation/gcp/index.md
> +- download the Control Plane's configuration file stored a secret
```suggestion
- download the Control Plane's configuration file, stored in a secret
```

2023-10-04 05:45 UTC, stb13579 commented on content/reference/admin/private_locations/installation/gcp/index.md
> +Required permissions:
Does the user need to enable these permissions? If so: "Enable the following required permissions:"

2023-10-04 05:45 UTC, stb13579 commented on content/reference/admin/private_locations/installation/gcp/index.md
> +Fill details with a name, an ID and a description for the control plane service account.
```suggestion
Fill details with:
- a name, 
- an ID, 
- a description of the control plane service account.
```

2023-10-04 05:45 UTC, stb13579 commented on content/reference/admin/private_locations/installation/gcp/index.md
> +Then, choose the role previously created.
```suggestion
Then, choose the previously created role.
```

2023-10-04 05:45 UTC, stb13579 commented on content/reference/admin/private_locations/installation/gcp/index.md
> +Click on "Done".
```suggestion
Click "Done".
```

2023-10-04 05:45 UTC, stb13579 commented on content/reference/admin/private_locations/installation/gcp/index.md
> +Set the name, region and zone of the VM instance.
```suggestion
Set the VM instance:
- name, 
- region, 
- zone.
```

2023-10-04 05:45 UTC, stb13579 commented on content/reference/admin/private_locations/installation/gcp/index.md
> +Machine type with less than 1 shared core and 2GB of memory may take up to 10 minutes to deploy properly the instance.
```suggestion
A machine type with less than 1 shared core and 2GB of memory may take up to 10 minutes to deploy the instance properly.
```

2023-10-04 05:45 UTC, stb13579 commented on content/reference/admin/private_locations/installation/gcp/index.md
> +Control plane configuration from secret manager will be download to host path further on.
```suggestion
The control plane configuration from the secret manager will be downloaded to the host path later.
```

2023-10-04 05:45 UTC, stb13579 commented on content/reference/admin/private_locations/installation/gcp/index.md
> +Control plane configuration from secret manager will be download to host path further on.
I don't completely understand this, so make sure my change makes sense!

2023-10-04 05:45 UTC, stb13579 commented on content/reference/admin/private_locations/installation/gcp/index.md
> +Configure the Identity and API access to the previously created service account.
```suggestion
Configure the Identity and API access for the previously created service account.
```

2023-10-04 05:45 UTC, stb13579 commented on content/reference/admin/private_locations/installation/gcp/index.md
> +Last step is to configure an automation that download the control plane configuration on start.
```suggestion
The last step is configuring an automation that downloads the control plane configuration on start.
```

2023-10-04 05:45 UTC, stb13579 commented on content/reference/admin/private_locations/installation/gcp/index.md
> +To do so, go to advanced options, on Management section set Automation startup script to:
```suggestion
To do so, go to advanced options in the Management section and set the Automation startup script to:
```

2023-10-04 05:45 UTC, stb13579 commented on content/reference/admin/private_locations/installation/gcp/index.md
> +This script download the control plane configuration secret from secret manager on disk, on a path mounted on the control plane container.
```suggestion
This script downloads the control plane configuration secret from the secret manager on the disk to a path mounted on the control plane container.
```

2023-10-04 05:45 UTC, stb13579 commented on content/reference/admin/private_locations/installation/gcp/index.md
> +This script download the control plane configuration secret from secret manager on disk, on a path mounted on the control plane container.
same comment, make sure I haven't changed the intended meaning

2023-10-04 05:45 UTC, stb13579 commented on content/reference/admin/private_locations/installation/gcp/index.md
> +You can now configure a simulation to run one one or more of this Control Plane's location!
```suggestion
You can now configure a simulation to run on one or more of this Control Plane's locations!
```

2023-10-04 08:42 UTC, tpetillot commented
Thanks a lot @stb13579 !

2023-10-06 12:17 UTC, Obero approved these changes
I agree with your doc, we just need to test it against reality with @bastien-gatling, who did not do a full set up like us.

2023-10-09 13:41 UTC, bastien-gatling approved these changes
Cool, juste a little comment !

2023-10-09 14:43 UTC, merged