Document gatling version badge on artifact table, closes MISC-92
gatling/frontline-cloud-doc pull request #24
Opened 2021-04-15 09:17 UTC by tpetillot

2021-04-15 09:37 UTC, slandelle requested changes

2021-04-15 09:38 UTC, slandelle commented on content/docs/user/artifact_conf/index.md
> +Artifact uploaded before the upload validation has been implemented may have a corrupted badge
corrupted -> "corrupted" (that's not the badge itself that's corrupted)

2021-04-15 13:33 UTC, ccedric commented on content/docs/user/artifact_conf/index.md
> +*(e.g: artifact hasn't be correctly generated)*
You should add that a corrupted artifact is not usable, and they need to fix it.

2021-04-16 07:31 UTC, notdryft approved these changes

2021-04-20 09:00 UTC, Isammoc approved these changes

2021-04-27 15:34 UTC, merged

2021-04-27 15:41 UTC, slandelle commented
Sad to merge this as I don't think this badge makes any sense and should probably go away.